name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x] # 单版本测试以简化调试，可扩展到多版本
      fail-fast: true

    steps:
    - uses: actions/checkout@v4

    - name: 设置 Node.js ${{ matrix.node-version }} 和 Yarn 4.6.0
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: yarn.lock

    - name: 启用 Corepack 并设置 Yarn 4.6.0
      run: |
        corepack enable
        corepack prepare yarn@4.6.0 --activate
        yarn --version  # 验证版本，应输出 4.6.0

    - name: 配置测试环境变量
      run: |
        cat <<EOT > .env.test
        DATABASE_URL="postgresql://testuser:testpass@localhost:5432/testdb"
        SECRET_KEY="test_secret_key_must_be_at_least_32_chars_long"
        REFRESH_SECRET_KEY="test_refresh_secret_key_must_be_32_chars"
        ALGORITHM="HS256"
        MAIL_USERNAME="test@example.com"
        MAIL_PASSWORD="testpassword"
        MAIL_FROM="test@example.com"
        MAIL_PORT=587
        MAIL_SERVER="smtp.test.com"
        MAIL_SSL_TLS=false
        MAIL_STARTTLS=true
        MAIL_USE_CREDENTIALS=true
        VERIFICATION_CODE_LENGTH=6
        VERIFICATION_CODE_EXPIRE_MINUTES=10
        REDIS_URL="redis://:localhost:6379/0"
        REDIS_PASSWORD=""
        REDIS_PORT=6379
        REDIS_DB=0
        GOOGLE_CLIENT_ID="test_google_client_id"
        GOOGLE_CLIENT_SECRET="test_google_client_secret"
        GITHUB_CLIENT_ID="test_github_client_id"
        GITHUB_CLIENT_SECRET="test_github_client_secret"
        BASE_URL="http://localhost:3000"
        ALLOWED_ORIGINS="http://localhost:3000"
        NODE_ENV="test"
        EOT

    - name: 安装依赖
      run: yarn install --frozen-lockfile

    - name: 运行测试
      run: yarn test
      env:
        CI: true

    - name: 上传覆盖率报告
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage
        fail_ci_if_error: false

    - name: 构建项目
      run: yarn build
      env:
        CI: true

  deploy:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: 设置 Node.js 22.x 和 Yarn 4.6.0
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'yarn'
        cache-dependency-path: yarn.lock

    - name: 启用 Corepack 并设置 Yarn 4.6.0
      run: |
        corepack enable
        corepack prepare yarn@4.6.0 --activate
        yarn --version  # 验证版本

    - name: 配置生产环境变量
      run: |
        cat <<EOT > .env.production
        DATABASE_URL="${{ secrets.DATABASE_URL }}"
        SECRET_KEY="${{ secrets.SECRET_KEY }}"
        REFRESH_SECRET_KEY="${{ secrets.REFRESH_SECRET_KEY }}"
        ALGORITHM="HS256"
        MAIL_USERNAME="${{ secrets.MAIL_USERNAME }}"
        MAIL_PASSWORD="${{ secrets.MAIL_PASSWORD }}"
        MAIL_FROM="${{ secrets.MAIL_FROM }}"
        MAIL_PORT=587
        MAIL_SERVER="smtp.gmail.com"
        MAIL_SSL_TLS=false
        MAIL_STARTTLS=true
        MAIL_USE_CREDENTIALS=true
        VERIFICATION_CODE_LENGTH=6
        VERIFICATION_CODE_EXPIRE_MINUTES=10
        REDIS_URL="${{ secrets.REDIS_URL }}"
        REDIS_PASSWORD="${{ secrets.REDIS_PASSWORD }}"
        REDIS_PORT=6379
        REDIS_DB=0
        GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}"
        GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}"
        GITHUB_CLIENT_ID="${{ secrets.GITHUB_CLIENT_ID }}"
        GITHUB_CLIENT_SECRET="${{ secrets.GITHUB_CLIENT_SECRET }}"
        BASE_URL="${{ secrets.PROD_BASE_URL }}"
        ALLOWED_ORIGINS="${{ secrets.PROD_ALLOWED_ORIGINS }}"
        NODE_ENV="production"
        EOT

    - name: 安装依赖
      run: yarn install --frozen-lockfile

    - name: 构建项目
      run: yarn build

    - name: 安装 Vercel CLI
      run: yarn global add vercel

    - name: 部署到 Vercel
      run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}